package iolang

// Code generated by mknumbermemo; DO NOT EDIT

import "math"

func (vm *VM) initIntsMemo() {
	vm.intsMemo = []*Number{
		&Number{Object: *vm.CoreInstance("Number"), Value: -1},
		&Number{Object: *vm.CoreInstance("Number"), Value: 0},
		&Number{Object: *vm.CoreInstance("Number"), Value: 1},
		&Number{Object: *vm.CoreInstance("Number"), Value: 2},
		&Number{Object: *vm.CoreInstance("Number"), Value: 3},
		&Number{Object: *vm.CoreInstance("Number"), Value: 4},
		&Number{Object: *vm.CoreInstance("Number"), Value: 5},
		&Number{Object: *vm.CoreInstance("Number"), Value: 6},
		&Number{Object: *vm.CoreInstance("Number"), Value: 7},
		&Number{Object: *vm.CoreInstance("Number"), Value: 8},
		&Number{Object: *vm.CoreInstance("Number"), Value: 9},
		&Number{Object: *vm.CoreInstance("Number"), Value: 10},
		&Number{Object: *vm.CoreInstance("Number"), Value: 11},
		&Number{Object: *vm.CoreInstance("Number"), Value: 12},
		&Number{Object: *vm.CoreInstance("Number"), Value: 13},
		&Number{Object: *vm.CoreInstance("Number"), Value: 14},
		&Number{Object: *vm.CoreInstance("Number"), Value: 15},
		&Number{Object: *vm.CoreInstance("Number"), Value: 16},
		&Number{Object: *vm.CoreInstance("Number"), Value: 17},
		&Number{Object: *vm.CoreInstance("Number"), Value: 18},
		&Number{Object: *vm.CoreInstance("Number"), Value: 19},
		&Number{Object: *vm.CoreInstance("Number"), Value: 20},
		&Number{Object: *vm.CoreInstance("Number"), Value: 21},
		&Number{Object: *vm.CoreInstance("Number"), Value: 22},
		&Number{Object: *vm.CoreInstance("Number"), Value: 23},
		&Number{Object: *vm.CoreInstance("Number"), Value: 24},
		&Number{Object: *vm.CoreInstance("Number"), Value: 25},
		&Number{Object: *vm.CoreInstance("Number"), Value: 26},
		&Number{Object: *vm.CoreInstance("Number"), Value: 27},
		&Number{Object: *vm.CoreInstance("Number"), Value: 28},
		&Number{Object: *vm.CoreInstance("Number"), Value: 29},
		&Number{Object: *vm.CoreInstance("Number"), Value: 30},
		&Number{Object: *vm.CoreInstance("Number"), Value: 31},
		&Number{Object: *vm.CoreInstance("Number"), Value: 32},
		&Number{Object: *vm.CoreInstance("Number"), Value: 33},
		&Number{Object: *vm.CoreInstance("Number"), Value: 34},
		&Number{Object: *vm.CoreInstance("Number"), Value: 35},
		&Number{Object: *vm.CoreInstance("Number"), Value: 36},
		&Number{Object: *vm.CoreInstance("Number"), Value: 37},
		&Number{Object: *vm.CoreInstance("Number"), Value: 38},
		&Number{Object: *vm.CoreInstance("Number"), Value: 39},
		&Number{Object: *vm.CoreInstance("Number"), Value: 40},
		&Number{Object: *vm.CoreInstance("Number"), Value: 41},
		&Number{Object: *vm.CoreInstance("Number"), Value: 42},
		&Number{Object: *vm.CoreInstance("Number"), Value: 43},
		&Number{Object: *vm.CoreInstance("Number"), Value: 44},
		&Number{Object: *vm.CoreInstance("Number"), Value: 45},
		&Number{Object: *vm.CoreInstance("Number"), Value: 46},
		&Number{Object: *vm.CoreInstance("Number"), Value: 47},
		&Number{Object: *vm.CoreInstance("Number"), Value: 48},
		&Number{Object: *vm.CoreInstance("Number"), Value: 49},
		&Number{Object: *vm.CoreInstance("Number"), Value: 50},
		&Number{Object: *vm.CoreInstance("Number"), Value: 51},
		&Number{Object: *vm.CoreInstance("Number"), Value: 52},
		&Number{Object: *vm.CoreInstance("Number"), Value: 53},
		&Number{Object: *vm.CoreInstance("Number"), Value: 54},
		&Number{Object: *vm.CoreInstance("Number"), Value: 55},
		&Number{Object: *vm.CoreInstance("Number"), Value: 56},
		&Number{Object: *vm.CoreInstance("Number"), Value: 57},
		&Number{Object: *vm.CoreInstance("Number"), Value: 58},
		&Number{Object: *vm.CoreInstance("Number"), Value: 59},
		&Number{Object: *vm.CoreInstance("Number"), Value: 60},
		&Number{Object: *vm.CoreInstance("Number"), Value: 61},
		&Number{Object: *vm.CoreInstance("Number"), Value: 62},
		&Number{Object: *vm.CoreInstance("Number"), Value: 63},
		&Number{Object: *vm.CoreInstance("Number"), Value: 64},
		&Number{Object: *vm.CoreInstance("Number"), Value: 65},
		&Number{Object: *vm.CoreInstance("Number"), Value: 66},
		&Number{Object: *vm.CoreInstance("Number"), Value: 67},
		&Number{Object: *vm.CoreInstance("Number"), Value: 68},
		&Number{Object: *vm.CoreInstance("Number"), Value: 69},
		&Number{Object: *vm.CoreInstance("Number"), Value: 70},
		&Number{Object: *vm.CoreInstance("Number"), Value: 71},
		&Number{Object: *vm.CoreInstance("Number"), Value: 72},
		&Number{Object: *vm.CoreInstance("Number"), Value: 73},
		&Number{Object: *vm.CoreInstance("Number"), Value: 74},
		&Number{Object: *vm.CoreInstance("Number"), Value: 75},
		&Number{Object: *vm.CoreInstance("Number"), Value: 76},
		&Number{Object: *vm.CoreInstance("Number"), Value: 77},
		&Number{Object: *vm.CoreInstance("Number"), Value: 78},
		&Number{Object: *vm.CoreInstance("Number"), Value: 79},
		&Number{Object: *vm.CoreInstance("Number"), Value: 80},
		&Number{Object: *vm.CoreInstance("Number"), Value: 81},
		&Number{Object: *vm.CoreInstance("Number"), Value: 82},
		&Number{Object: *vm.CoreInstance("Number"), Value: 83},
		&Number{Object: *vm.CoreInstance("Number"), Value: 84},
		&Number{Object: *vm.CoreInstance("Number"), Value: 85},
		&Number{Object: *vm.CoreInstance("Number"), Value: 86},
		&Number{Object: *vm.CoreInstance("Number"), Value: 87},
		&Number{Object: *vm.CoreInstance("Number"), Value: 88},
		&Number{Object: *vm.CoreInstance("Number"), Value: 89},
		&Number{Object: *vm.CoreInstance("Number"), Value: 90},
		&Number{Object: *vm.CoreInstance("Number"), Value: 91},
		&Number{Object: *vm.CoreInstance("Number"), Value: 92},
		&Number{Object: *vm.CoreInstance("Number"), Value: 93},
		&Number{Object: *vm.CoreInstance("Number"), Value: 94},
		&Number{Object: *vm.CoreInstance("Number"), Value: 95},
		&Number{Object: *vm.CoreInstance("Number"), Value: 96},
		&Number{Object: *vm.CoreInstance("Number"), Value: 97},
		&Number{Object: *vm.CoreInstance("Number"), Value: 98},
		&Number{Object: *vm.CoreInstance("Number"), Value: 99},
		&Number{Object: *vm.CoreInstance("Number"), Value: 100},
		&Number{Object: *vm.CoreInstance("Number"), Value: 101},
		&Number{Object: *vm.CoreInstance("Number"), Value: 102},
		&Number{Object: *vm.CoreInstance("Number"), Value: 103},
		&Number{Object: *vm.CoreInstance("Number"), Value: 104},
		&Number{Object: *vm.CoreInstance("Number"), Value: 105},
		&Number{Object: *vm.CoreInstance("Number"), Value: 106},
		&Number{Object: *vm.CoreInstance("Number"), Value: 107},
		&Number{Object: *vm.CoreInstance("Number"), Value: 108},
		&Number{Object: *vm.CoreInstance("Number"), Value: 109},
		&Number{Object: *vm.CoreInstance("Number"), Value: 110},
		&Number{Object: *vm.CoreInstance("Number"), Value: 111},
		&Number{Object: *vm.CoreInstance("Number"), Value: 112},
		&Number{Object: *vm.CoreInstance("Number"), Value: 113},
		&Number{Object: *vm.CoreInstance("Number"), Value: 114},
		&Number{Object: *vm.CoreInstance("Number"), Value: 115},
		&Number{Object: *vm.CoreInstance("Number"), Value: 116},
		&Number{Object: *vm.CoreInstance("Number"), Value: 117},
		&Number{Object: *vm.CoreInstance("Number"), Value: 118},
		&Number{Object: *vm.CoreInstance("Number"), Value: 119},
		&Number{Object: *vm.CoreInstance("Number"), Value: 120},
		&Number{Object: *vm.CoreInstance("Number"), Value: 121},
		&Number{Object: *vm.CoreInstance("Number"), Value: 122},
		&Number{Object: *vm.CoreInstance("Number"), Value: 123},
		&Number{Object: *vm.CoreInstance("Number"), Value: 124},
		&Number{Object: *vm.CoreInstance("Number"), Value: 125},
		&Number{Object: *vm.CoreInstance("Number"), Value: 126},
		&Number{Object: *vm.CoreInstance("Number"), Value: 127},
		&Number{Object: *vm.CoreInstance("Number"), Value: 128},
		&Number{Object: *vm.CoreInstance("Number"), Value: 129},
		&Number{Object: *vm.CoreInstance("Number"), Value: 130},
		&Number{Object: *vm.CoreInstance("Number"), Value: 131},
		&Number{Object: *vm.CoreInstance("Number"), Value: 132},
		&Number{Object: *vm.CoreInstance("Number"), Value: 133},
		&Number{Object: *vm.CoreInstance("Number"), Value: 134},
		&Number{Object: *vm.CoreInstance("Number"), Value: 135},
		&Number{Object: *vm.CoreInstance("Number"), Value: 136},
		&Number{Object: *vm.CoreInstance("Number"), Value: 137},
		&Number{Object: *vm.CoreInstance("Number"), Value: 138},
		&Number{Object: *vm.CoreInstance("Number"), Value: 139},
		&Number{Object: *vm.CoreInstance("Number"), Value: 140},
		&Number{Object: *vm.CoreInstance("Number"), Value: 141},
		&Number{Object: *vm.CoreInstance("Number"), Value: 142},
		&Number{Object: *vm.CoreInstance("Number"), Value: 143},
		&Number{Object: *vm.CoreInstance("Number"), Value: 144},
		&Number{Object: *vm.CoreInstance("Number"), Value: 145},
		&Number{Object: *vm.CoreInstance("Number"), Value: 146},
		&Number{Object: *vm.CoreInstance("Number"), Value: 147},
		&Number{Object: *vm.CoreInstance("Number"), Value: 148},
		&Number{Object: *vm.CoreInstance("Number"), Value: 149},
		&Number{Object: *vm.CoreInstance("Number"), Value: 150},
		&Number{Object: *vm.CoreInstance("Number"), Value: 151},
		&Number{Object: *vm.CoreInstance("Number"), Value: 152},
		&Number{Object: *vm.CoreInstance("Number"), Value: 153},
		&Number{Object: *vm.CoreInstance("Number"), Value: 154},
		&Number{Object: *vm.CoreInstance("Number"), Value: 155},
		&Number{Object: *vm.CoreInstance("Number"), Value: 156},
		&Number{Object: *vm.CoreInstance("Number"), Value: 157},
		&Number{Object: *vm.CoreInstance("Number"), Value: 158},
		&Number{Object: *vm.CoreInstance("Number"), Value: 159},
		&Number{Object: *vm.CoreInstance("Number"), Value: 160},
		&Number{Object: *vm.CoreInstance("Number"), Value: 161},
		&Number{Object: *vm.CoreInstance("Number"), Value: 162},
		&Number{Object: *vm.CoreInstance("Number"), Value: 163},
		&Number{Object: *vm.CoreInstance("Number"), Value: 164},
		&Number{Object: *vm.CoreInstance("Number"), Value: 165},
		&Number{Object: *vm.CoreInstance("Number"), Value: 166},
		&Number{Object: *vm.CoreInstance("Number"), Value: 167},
		&Number{Object: *vm.CoreInstance("Number"), Value: 168},
		&Number{Object: *vm.CoreInstance("Number"), Value: 169},
		&Number{Object: *vm.CoreInstance("Number"), Value: 170},
		&Number{Object: *vm.CoreInstance("Number"), Value: 171},
		&Number{Object: *vm.CoreInstance("Number"), Value: 172},
		&Number{Object: *vm.CoreInstance("Number"), Value: 173},
		&Number{Object: *vm.CoreInstance("Number"), Value: 174},
		&Number{Object: *vm.CoreInstance("Number"), Value: 175},
		&Number{Object: *vm.CoreInstance("Number"), Value: 176},
		&Number{Object: *vm.CoreInstance("Number"), Value: 177},
		&Number{Object: *vm.CoreInstance("Number"), Value: 178},
		&Number{Object: *vm.CoreInstance("Number"), Value: 179},
		&Number{Object: *vm.CoreInstance("Number"), Value: 180},
		&Number{Object: *vm.CoreInstance("Number"), Value: 181},
		&Number{Object: *vm.CoreInstance("Number"), Value: 182},
		&Number{Object: *vm.CoreInstance("Number"), Value: 183},
		&Number{Object: *vm.CoreInstance("Number"), Value: 184},
		&Number{Object: *vm.CoreInstance("Number"), Value: 185},
		&Number{Object: *vm.CoreInstance("Number"), Value: 186},
		&Number{Object: *vm.CoreInstance("Number"), Value: 187},
		&Number{Object: *vm.CoreInstance("Number"), Value: 188},
		&Number{Object: *vm.CoreInstance("Number"), Value: 189},
		&Number{Object: *vm.CoreInstance("Number"), Value: 190},
		&Number{Object: *vm.CoreInstance("Number"), Value: 191},
		&Number{Object: *vm.CoreInstance("Number"), Value: 192},
		&Number{Object: *vm.CoreInstance("Number"), Value: 193},
		&Number{Object: *vm.CoreInstance("Number"), Value: 194},
		&Number{Object: *vm.CoreInstance("Number"), Value: 195},
		&Number{Object: *vm.CoreInstance("Number"), Value: 196},
		&Number{Object: *vm.CoreInstance("Number"), Value: 197},
		&Number{Object: *vm.CoreInstance("Number"), Value: 198},
		&Number{Object: *vm.CoreInstance("Number"), Value: 199},
		&Number{Object: *vm.CoreInstance("Number"), Value: 200},
		&Number{Object: *vm.CoreInstance("Number"), Value: 201},
		&Number{Object: *vm.CoreInstance("Number"), Value: 202},
		&Number{Object: *vm.CoreInstance("Number"), Value: 203},
		&Number{Object: *vm.CoreInstance("Number"), Value: 204},
		&Number{Object: *vm.CoreInstance("Number"), Value: 205},
		&Number{Object: *vm.CoreInstance("Number"), Value: 206},
		&Number{Object: *vm.CoreInstance("Number"), Value: 207},
		&Number{Object: *vm.CoreInstance("Number"), Value: 208},
		&Number{Object: *vm.CoreInstance("Number"), Value: 209},
		&Number{Object: *vm.CoreInstance("Number"), Value: 210},
		&Number{Object: *vm.CoreInstance("Number"), Value: 211},
		&Number{Object: *vm.CoreInstance("Number"), Value: 212},
		&Number{Object: *vm.CoreInstance("Number"), Value: 213},
		&Number{Object: *vm.CoreInstance("Number"), Value: 214},
		&Number{Object: *vm.CoreInstance("Number"), Value: 215},
		&Number{Object: *vm.CoreInstance("Number"), Value: 216},
		&Number{Object: *vm.CoreInstance("Number"), Value: 217},
		&Number{Object: *vm.CoreInstance("Number"), Value: 218},
		&Number{Object: *vm.CoreInstance("Number"), Value: 219},
		&Number{Object: *vm.CoreInstance("Number"), Value: 220},
		&Number{Object: *vm.CoreInstance("Number"), Value: 221},
		&Number{Object: *vm.CoreInstance("Number"), Value: 222},
		&Number{Object: *vm.CoreInstance("Number"), Value: 223},
		&Number{Object: *vm.CoreInstance("Number"), Value: 224},
		&Number{Object: *vm.CoreInstance("Number"), Value: 225},
		&Number{Object: *vm.CoreInstance("Number"), Value: 226},
		&Number{Object: *vm.CoreInstance("Number"), Value: 227},
		&Number{Object: *vm.CoreInstance("Number"), Value: 228},
		&Number{Object: *vm.CoreInstance("Number"), Value: 229},
		&Number{Object: *vm.CoreInstance("Number"), Value: 230},
		&Number{Object: *vm.CoreInstance("Number"), Value: 231},
		&Number{Object: *vm.CoreInstance("Number"), Value: 232},
		&Number{Object: *vm.CoreInstance("Number"), Value: 233},
		&Number{Object: *vm.CoreInstance("Number"), Value: 234},
		&Number{Object: *vm.CoreInstance("Number"), Value: 235},
		&Number{Object: *vm.CoreInstance("Number"), Value: 236},
		&Number{Object: *vm.CoreInstance("Number"), Value: 237},
		&Number{Object: *vm.CoreInstance("Number"), Value: 238},
		&Number{Object: *vm.CoreInstance("Number"), Value: 239},
		&Number{Object: *vm.CoreInstance("Number"), Value: 240},
		&Number{Object: *vm.CoreInstance("Number"), Value: 241},
		&Number{Object: *vm.CoreInstance("Number"), Value: 242},
		&Number{Object: *vm.CoreInstance("Number"), Value: 243},
		&Number{Object: *vm.CoreInstance("Number"), Value: 244},
		&Number{Object: *vm.CoreInstance("Number"), Value: 245},
		&Number{Object: *vm.CoreInstance("Number"), Value: 246},
		&Number{Object: *vm.CoreInstance("Number"), Value: 247},
		&Number{Object: *vm.CoreInstance("Number"), Value: 248},
		&Number{Object: *vm.CoreInstance("Number"), Value: 249},
		&Number{Object: *vm.CoreInstance("Number"), Value: 250},
		&Number{Object: *vm.CoreInstance("Number"), Value: 251},
		&Number{Object: *vm.CoreInstance("Number"), Value: 252},
		&Number{Object: *vm.CoreInstance("Number"), Value: 253},
		&Number{Object: *vm.CoreInstance("Number"), Value: 254},
		&Number{Object: *vm.CoreInstance("Number"), Value: 255},
	}
}

func (vm *VM) chkIntsMemo(x float64) *Number {
	z := int32(x)
	if float64(z) == x && -1 <= z && z <= 255 {
		return vm.intsMemo[z - -1]
	}
	return nil
}

type realsMemo struct {
	e          *Number
	eps        *Number
	fourth     *Number
	half       *Number
	inf        *Number
	ln10       *Number
	ln2        *Number
	log10e     *Number
	log2e      *Number
	maxFloat64 *Number
	maxInt16   *Number
	maxInt64   *Number
	minInt16   *Number
	minInt64   *Number
	ninf       *Number
	phi        *Number
	pi         *Number
	sqrt2      *Number
	sqrtE      *Number
	sqrtPhi    *Number
	sqrtPi     *Number
	third      *Number
}

func (vm *VM) initRealsMemo() {
	vm.realsMemo = &realsMemo{
		e:          &Number{Object: *vm.CoreInstance("Number"), Value: math.E},
		eps:        &Number{Object: *vm.CoreInstance("Number"), Value: math.SmallestNonzeroFloat64},
		fourth:     &Number{Object: *vm.CoreInstance("Number"), Value: 0.25},
		half:       &Number{Object: *vm.CoreInstance("Number"), Value: 0.5},
		inf:        &Number{Object: *vm.CoreInstance("Number"), Value: math.Inf(1)},
		ln10:       &Number{Object: *vm.CoreInstance("Number"), Value: math.Ln10},
		ln2:        &Number{Object: *vm.CoreInstance("Number"), Value: math.Ln2},
		log10e:     &Number{Object: *vm.CoreInstance("Number"), Value: math.Log10E},
		log2e:      &Number{Object: *vm.CoreInstance("Number"), Value: math.Log2E},
		maxFloat64: &Number{Object: *vm.CoreInstance("Number"), Value: math.MaxFloat64},
		maxInt16:   &Number{Object: *vm.CoreInstance("Number"), Value: math.MaxInt16},
		maxInt64:   &Number{Object: *vm.CoreInstance("Number"), Value: math.MaxInt64},
		minInt16:   &Number{Object: *vm.CoreInstance("Number"), Value: math.MinInt16},
		minInt64:   &Number{Object: *vm.CoreInstance("Number"), Value: math.MinInt64},
		ninf:       &Number{Object: *vm.CoreInstance("Number"), Value: math.Inf(-1)},
		phi:        &Number{Object: *vm.CoreInstance("Number"), Value: math.Phi},
		pi:         &Number{Object: *vm.CoreInstance("Number"), Value: math.Pi},
		sqrt2:      &Number{Object: *vm.CoreInstance("Number"), Value: math.Sqrt2},
		sqrtE:      &Number{Object: *vm.CoreInstance("Number"), Value: math.SqrtE},
		sqrtPhi:    &Number{Object: *vm.CoreInstance("Number"), Value: math.SqrtPhi},
		sqrtPi:     &Number{Object: *vm.CoreInstance("Number"), Value: math.SqrtPi},
		third:      &Number{Object: *vm.CoreInstance("Number"), Value: 0.33333333333333333},
	}
}

func (vm *VM) chkRealsMemo(x float64) *Number {
	switch x {
	case math.E:
		return vm.realsMemo.e
	case math.SmallestNonzeroFloat64:
		return vm.realsMemo.eps
	case 0.25:
		return vm.realsMemo.fourth
	case 0.5:
		return vm.realsMemo.half
	case math.Inf(1):
		return vm.realsMemo.inf
	case math.Ln10:
		return vm.realsMemo.ln10
	case math.Ln2:
		return vm.realsMemo.ln2
	case math.Log10E:
		return vm.realsMemo.log10e
	case math.Log2E:
		return vm.realsMemo.log2e
	case math.MaxFloat64:
		return vm.realsMemo.maxFloat64
	case math.MaxInt16:
		return vm.realsMemo.maxInt16
	case math.MaxInt64:
		return vm.realsMemo.maxInt64
	case math.MinInt16:
		return vm.realsMemo.minInt16
	case math.MinInt64:
		return vm.realsMemo.minInt64
	case math.Inf(-1):
		return vm.realsMemo.ninf
	case math.Phi:
		return vm.realsMemo.phi
	case math.Pi:
		return vm.realsMemo.pi
	case math.Sqrt2:
		return vm.realsMemo.sqrt2
	case math.SqrtE:
		return vm.realsMemo.sqrtE
	case math.SqrtPhi:
		return vm.realsMemo.sqrtPhi
	case math.SqrtPi:
		return vm.realsMemo.sqrtPi
	case 0.33333333333333333:
		return vm.realsMemo.third

	}
	return nil
}
