package iolang

// Code generated by mknumbermemo; DO NOT EDIT

import "math"

func (vm *VM) initIntsMemo() {
	vm.intsMemo = []*Number{
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: -1},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 0},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 1},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 2},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 3},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 4},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 5},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 6},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 7},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 8},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 9},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 10},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 11},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 12},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 13},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 14},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 15},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 16},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 17},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 18},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 19},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 20},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 21},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 22},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 23},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 24},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 25},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 26},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 27},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 28},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 29},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 30},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 31},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 32},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 33},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 34},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 35},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 36},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 37},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 38},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 39},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 40},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 41},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 42},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 43},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 44},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 45},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 46},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 47},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 48},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 49},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 50},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 51},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 52},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 53},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 54},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 55},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 56},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 57},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 58},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 59},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 60},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 61},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 62},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 63},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 64},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 65},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 66},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 67},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 68},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 69},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 70},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 71},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 72},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 73},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 74},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 75},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 76},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 77},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 78},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 79},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 80},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 81},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 82},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 83},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 84},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 85},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 86},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 87},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 88},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 89},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 90},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 91},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 92},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 93},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 94},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 95},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 96},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 97},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 98},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 99},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 100},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 101},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 102},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 103},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 104},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 105},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 106},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 107},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 108},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 109},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 110},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 111},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 112},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 113},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 114},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 115},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 116},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 117},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 118},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 119},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 120},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 121},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 122},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 123},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 124},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 125},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 126},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 127},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 128},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 129},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 130},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 131},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 132},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 133},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 134},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 135},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 136},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 137},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 138},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 139},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 140},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 141},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 142},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 143},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 144},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 145},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 146},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 147},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 148},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 149},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 150},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 151},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 152},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 153},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 154},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 155},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 156},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 157},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 158},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 159},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 160},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 161},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 162},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 163},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 164},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 165},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 166},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 167},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 168},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 169},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 170},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 171},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 172},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 173},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 174},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 175},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 176},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 177},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 178},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 179},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 180},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 181},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 182},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 183},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 184},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 185},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 186},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 187},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 188},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 189},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 190},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 191},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 192},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 193},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 194},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 195},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 196},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 197},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 198},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 199},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 200},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 201},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 202},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 203},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 204},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 205},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 206},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 207},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 208},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 209},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 210},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 211},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 212},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 213},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 214},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 215},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 216},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 217},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 218},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 219},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 220},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 221},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 222},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 223},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 224},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 225},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 226},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 227},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 228},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 229},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 230},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 231},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 232},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 233},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 234},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 235},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 236},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 237},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 238},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 239},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 240},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 241},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 242},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 243},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 244},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 245},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 246},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 247},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 248},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 249},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 250},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 251},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 252},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 253},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 254},
		{Object: Object{Protos: vm.CoreProto("Number")}, Value: 255},
	}
}

func (vm *VM) chkIntsMemo(x float64) *Number {
	z := int32(x)
	if float64(z) == x && -1 <= z && z <= 255 {
		return vm.intsMemo[z - -1]
	}
	return nil
}

type realsMemo struct {
	e          *Number
	eps        *Number
	fourth     *Number
	half       *Number
	inf        *Number
	ln10       *Number
	ln2        *Number
	log10e     *Number
	log2e      *Number
	maxFloat64 *Number
	maxInt16   *Number
	maxInt64   *Number
	minInt16   *Number
	minInt64   *Number
	ninf       *Number
	phi        *Number
	pi         *Number
	sqrt2      *Number
	sqrtE      *Number
	sqrtPhi    *Number
	sqrtPi     *Number
	third      *Number
}

func (vm *VM) initRealsMemo() {
	vm.realsMemo = &realsMemo{
		e:          &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.E},
		eps:        &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.SmallestNonzeroFloat64},
		fourth:     &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: 0.25},
		half:       &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: 0.5},
		inf:        &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.Inf(1)},
		ln10:       &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.Ln10},
		ln2:        &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.Ln2},
		log10e:     &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.Log10E},
		log2e:      &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.Log2E},
		maxFloat64: &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.MaxFloat64},
		maxInt16:   &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.MaxInt16},
		maxInt64:   &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.MaxInt64},
		minInt16:   &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.MinInt16},
		minInt64:   &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.MinInt64},
		ninf:       &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.Inf(-1)},
		phi:        &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.Phi},
		pi:         &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.Pi},
		sqrt2:      &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.Sqrt2},
		sqrtE:      &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.SqrtE},
		sqrtPhi:    &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.SqrtPhi},
		sqrtPi:     &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: math.SqrtPi},
		third:      &Number{Object: Object{Protos: vm.CoreProto("Number")}, Value: 0.33333333333333333},
	}
}

func (vm *VM) chkRealsMemo(x float64) *Number {
	switch x {
	case math.E:
		return vm.realsMemo.e
	case math.SmallestNonzeroFloat64:
		return vm.realsMemo.eps
	case 0.25:
		return vm.realsMemo.fourth
	case 0.5:
		return vm.realsMemo.half
	case math.Inf(1):
		return vm.realsMemo.inf
	case math.Ln10:
		return vm.realsMemo.ln10
	case math.Ln2:
		return vm.realsMemo.ln2
	case math.Log10E:
		return vm.realsMemo.log10e
	case math.Log2E:
		return vm.realsMemo.log2e
	case math.MaxFloat64:
		return vm.realsMemo.maxFloat64
	case math.MaxInt16:
		return vm.realsMemo.maxInt16
	case math.MaxInt64:
		return vm.realsMemo.maxInt64
	case math.MinInt16:
		return vm.realsMemo.minInt16
	case math.MinInt64:
		return vm.realsMemo.minInt64
	case math.Inf(-1):
		return vm.realsMemo.ninf
	case math.Phi:
		return vm.realsMemo.phi
	case math.Pi:
		return vm.realsMemo.pi
	case math.Sqrt2:
		return vm.realsMemo.sqrt2
	case math.SqrtE:
		return vm.realsMemo.sqrtE
	case math.SqrtPhi:
		return vm.realsMemo.sqrtPhi
	case math.SqrtPi:
		return vm.realsMemo.sqrtPi
	case 0.33333333333333333:
		return vm.realsMemo.third

	}
	return nil
}
