name: Tests
on: [push, pull_request]
jobs:
  testCore:
    name: Test Core
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Set up environment variables
      run: |
        go env -w GO111MODULE=on
        go env -w GOPATH=$HOME
        go mod init CI
      
    - name: Install the repository and dependencies
      run: go get -v -t github.com/$GITHUB_REPOSITORY@$GITHUB_SHA

    - name: Check that all subpackages build
      run: go build -v github.com/$GITHUB_REPOSITORY/...
        
    - name: Run tests
      run: |
        go test github.com/$GITHUB_REPOSITORY/...
        go test -race -count=3 github.com/$GITHUB_REPOSITORY/...
